#Database Configuration
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices
  application:
    name: RATING-SERVICE
  config:
    import: optional:configserver://localhost:8085
  profiles:
    active: dev   
   
server:
  port: 0

eureka:
  instance:
    instance-id: RATING-SERVICE:${spring.application.instance_id:${random.value}}

