server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          default-label: master
          search-paths: Microservices1_Configurations
          uri: https://github.com/PranaySingh13/microservices-configurations.git
